### ISSUE TITLE
KBCT crashes after system being suspended

### ISSUE THREAD

**Issue by mzenz** [samvel1024/kbct#15]
First of all, thanks so much for this life-saving project, it really saved the day for me. Let me know if you need any extra info, happy to dig deeper! =)

# Description:

KBCT crashes after system is suspended and resumed.

# Command (running as root):

`$ /usr/local/bin/kbct remap --config /etc/kbct/config.yml`

# Configuration
Disable PageUp & PageDown keys altogether:

```
- keyboards: [ "AT Translated Set 2 keyboard"]
  keymap:
    pageup: reserved
    pagedown: reserved
```
# Log output

```
 INFO  kbct > Starting kbct event loop, pid=7319
 INFO  kbct > Capturing device path=/dev/input/event2 name="AT Translated Set 2 keyboard" mapped_name="Kbct-AT Translated Set 2 keyboard"
Error: IOError(Os { code: 4, kind: Interrupted, message: "Interrupted system call" })
```
# System info
```
OS: Ubuntu 21.10 x86_64 
Host: XPS 13 9310 2-in-1 
Kernel: 5.13.0-22-generic 
Uptime: 15 mins 
Packages: 1783 (dpkg), 17 (snap) 
Shell: fish 3.1.2 
Resolution: 3840x2400 
WM: Mutter 
Terminal: terminator 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 5074MiB / 31819MiB 
```

**Comment by samvel1024** [comment]
Thank you @mzenz for the detailed report. Can you please repeat the same scenario with `RUST_BACKTRACE` env var set to 1 and provide the backtrace of the error.

```
export RUST_BACKTRACE=1 
sudo -E /usr/local/bin/kbct remap --config /etc/kbct/config.yml
```

**Comment by mzenz** [comment]
Hi. I get exactly the exact same output

**Comment by mzenz** [comment]
Even with that variable set as you describe, I get the exact same output as far as I can tell:

```
 INFO  kbct > Starting kbct event loop, pid=5939
 INFO  kbct > Capturing device path=/dev/input/event2 name="AT Translated Set 2 keyboard" mapped_name="Kbct-AT Translated Set 2 keyboard"
Error: IOError(Os { code: 4, kind: Interrupted, message: "Interrupted system call" })
```

**Comment by jerry-sky** [comment]
I’ve also stumbled upon this issue. I come with no further information, as I receive the same logs when suspending the computer whilst running KBCT.

However, I wanted to bump this issue and ask whether there are any updates on this?

**Comment by seltzered** [comment]
FWIW, I just started noticing this issue occurring much more after switching from Ubuntu 21.10 to 22.04 (Wayland on both installs), tried running with RUST_BACKTRACE=1 and similarly only got `Error: IOError(Os { code: 4, kind: Interrupted, message: "Interrupted system call" })`. 

While I do have kbct setup to run at system start I haven't considered auto-restart yet like the above comment. My workaround so far has been to just keep a `restart_kbct.sh` script that can easily be invoked from a launcher tool (e.g. `pkexec /path/to/kbct remap --config /path/to/my/config.yaml &`)
