### ISSUE TITLE
Support remapping mouse buttons

### ISSUE THREAD

**Issue by felagund** [samvel1024/kbct#21]
Not sure how hard it would be and if it is out of scope, but remapping mouse buttons would be great. Especially if one could emit keyboard keys with them or other way around (pressing a key to emit a middle button to paste, for example).

**Comment by samvel1024** [comment]
You can easily achieve that by writing the name of the mouse in `keyboards` field. Copy-pasting might not be possible because one to many keystroke mapping is not possible as of now. So no special support for mouses is really needed.

**Comment by felagund** [comment]
Oh, perfect!
