### ISSUE TITLE
Do layers work across devices?

### ISSUE THREAD

**Issue by 101100** [samvel1024/kbct#28]
If I have a mouse and keyboard that are both controlled by `kbct`, would it be possible to define a layer from a keyboard key that would affect the mouse button actions?

**Comment by filyp** [comment]
I have a similar use case, but trying to do combinations with two keyboard devices.
This feature would be really useful.

**Comment by samvel1024** [comment]
@101100 This is something that I also thought about. Will include this in the roadmap. 

Thank you!
